name: Build & Deploy ðŸš€
on: [push]
jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    env:
      USE_SSH: false
      GIT_USER: Flixkatz
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - run: git config --global user.email "github-actions@example.com"
      - run: git config --global user.name "GitHub Actions"
      - uses: actions/checkout@v3
      - run: npm install
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          git-user: Flixbox
