name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  call-checks:
    name: Run checks
    uses: ./.github/workflows/checks.yml

  call-preview:
    name: Build preview
    uses: ./.github/workflows/preview.yml

  call-preview-app-list-service:
    name: Deploy preview for app list service
    uses: ./.github/workflows/preview-app-list-service.yml
