name: Workers PR Preview

on:
  workflow_call:
    secrets:
      CF_API_TOKEN:
        required: true
      CF_ACCOUNT_ID:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Verify required variables
        run: |
          : "${CF_API_TOKEN:?CF_API_TOKEN is not set or empty}"
          : "${CF_ACCOUNT_ID:?CF_ACCOUNT_ID is not set or empty}"
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen

      - id: preview_step
        uses: shidil/cloudflare-workers-preview@v1
        with:
          cf_token: ${{ secrets.CF_API_TOKEN }}
          cf_account: ${{ secrets.CF_ACCOUNT_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          domain: lp-compat-backend.alone-king-poking.workers.dev
          project_path: packages/app-list-service
          failOnError: true
          teardown: 'true'
          build: |
            echo "No build necessary"
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"